<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buat Akun</name>
   <tag></tag>
   <elementGuidId>53353e74-f5bf-405b-b8fa-9d8e23fac773</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-menu-register-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='account-menu-register-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8bb80f1d-8901-4309-a522-4b391f99d6a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>customer/account/create/?from=header</value>
      <webElementGuid>8bf258fd-aab1-4c44-a307-0d3c0bb41214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Buat Akun</value>
      <webElementGuid>7f41cc60-01dc-4d0f-b901-b0bdb7db480f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>follow</value>
      <webElementGuid>a4e9390c-e4b9-4eb6-8900-80e5abc5c9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-menu-register-btn</value>
      <webElementGuid>df5ebd13-939c-42b0-a934-60d1c59ce80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                        Buat Akun                                    </value>
      <webElementGuid>3ac7bc74-5983-46b8-9c11-500f8afb951d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-menu-register-btn&quot;)</value>
      <webElementGuid>5c63c395-9b3b-476e-89e9-2f95eaafb1b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='account-menu-register-btn']</value>
      <webElementGuid>6b00ed91-adab-4b71-a4d9-0a39a800abac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='seg-bar__utils']/li/div/div[3]/ul/li[2]/a</value>
      <webElementGuid>2c5466d9-c827-4859-ad6a-66948ec87673</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buat Akun')]</value>
      <webElementGuid>83b5e8bc-e5fa-4f12-a6f1-f6b29c3ecc1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[1]/following::a[1]</value>
      <webElementGuid>3c02ac52-5689-465b-a87a-0c2ed474ec20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selamat datang!'])[1]/following::a[2]</value>
      <webElementGuid>acfd3e08-e2c5-43f6-8aee-c637e19ac4c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lihat Status Pesanan'])[1]/preceding::a[1]</value>
      <webElementGuid>81814cd9-df09-445d-8a08-2fb91c717d19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi Transfer'])[1]/preceding::a[2]</value>
      <webElementGuid>bafe5022-d6c0-4a95-a474-dedf358f9138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buat Akun']/parent::*</value>
      <webElementGuid>31027c5d-5fb4-4b22-943e-e70faf09ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'customer/account/create/?from=header')]</value>
      <webElementGuid>c76dcdbf-4d32-4be1-9481-6ec48ba9fb18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/ul/li[2]/a</value>
      <webElementGuid>acff9673-7065-4168-9ba0-905d1cd6023e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'customer/account/create/?from=header' and @title = 'Buat Akun' and @id = 'account-menu-register-btn' and (text() = '
                                        Buat Akun                                    ' or . = '
                                        Buat Akun                                    ')]</value>
      <webElementGuid>34c71755-d782-4033-ac42-b9434413538e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
