<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan kode OTP yang Anda terima di _3172c7</name>
   <tag></tag>
   <elementGuidId>4bab333c-ff80-4a1a-aa3c-14f28823fdfa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#digit-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digit-3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>80ac1129-28e0-4f6e-a7ef-287c9c2f8f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input input-text</value>
      <webElementGuid>0d2aba0e-84ab-4d78-b5da-34e030524328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b184c07f-a8b2-41a6-8f62-f30723f6f2c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>a28e5230-1a3c-4aa6-8cde-036f0cda4c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digit-3</value>
      <webElementGuid>899feaca-7e11-4c2f-9624-370632d442ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp[digit-3]</value>
      <webElementGuid>b6402eb1-b22c-4988-a217-76040021f80d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-next</name>
      <type>Main</type>
      <value>digit-4</value>
      <webElementGuid>b20b43a6-30e5-4ce9-9077-0ee9a2bb5710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previous</name>
      <type>Main</type>
      <value>digit-2</value>
      <webElementGuid>c03cca86-2680-4ad1-89f0-bb909837a90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9a57acda-49a2-4008-89f2-325fd1d9678e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digit-3&quot;)</value>
      <webElementGuid>3cc819c2-9a88-4684-9423-a628da2ccac6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digit-3']</value>
      <webElementGuid>84ba34d0-217d-4140-84d3-9b7f6986d5f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp']/div/input[3]</value>
      <webElementGuid>6a7f544b-6cb9-46a7-8d32-8a9a7d597c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>74dc1bb9-ee44-4d27-9d01-648890fc4fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'digit-3' and @name = 'otp[digit-3]']</value>
      <webElementGuid>796cb1ff-11a9-473b-b50c-38fec9558dff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
