<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_No. Handphone_phone_number</name>
   <tag></tag>
   <elementGuidId>3c70a766-cc33-42ec-a6b8-05dd11a7a7a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#telephone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='telephone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>09efc26f-2405-4b8f-ada0-a2385764c592</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9156fa57-9a9e-428b-893c-3808365b4b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>4b806628-3776-4793-b648-226396908279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone_number</value>
      <webElementGuid>aafe398a-a315-47bc-b163-871bd5f3af45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>telephone</value>
      <webElementGuid>aed00cb4-6618-4ca4-87d6-482ad57dbae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>08123456789</value>
      <webElementGuid>e19d6e35-0178-44e9-b901-efe8b98db92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nomor telepon</value>
      <webElementGuid>ad68947d-56f8-481e-86c7-2216dc4aa69a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text required-entry validate-digits minimum-length-6 maximum-length-15 validate-length</value>
      <webElementGuid>3f30b7f0-01f5-47c5-9c75-2b36e05ddcf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true, 'validatePhoneNumber':true}</value>
      <webElementGuid>59056733-31f0-4cca-9640-2b0bb3c97024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6d81bf01-1187-4a16-943a-1d7251f62a37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;telephone&quot;)</value>
      <webElementGuid>cce0acf5-bfe6-47c0-a6e1-2dd14ea294d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='telephone']</value>
      <webElementGuid>00bdbba8-4ee3-4f7c-80dc-8fd40ded0eb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[4]/div/input</value>
      <webElementGuid>4bb55b4b-17ec-406e-b10c-643a37b22ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>4c503065-90b6-43dd-a6d4-95a208513297</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'phone_number' and @id = 'telephone' and @placeholder = '08123456789' and @title = 'Nomor telepon']</value>
      <webElementGuid>989f0110-4af1-45b3-8c37-6c35902cdae5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
