<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan kode OTP yang Anda terima di _e3d219</name>
   <tag></tag>
   <elementGuidId>ece204c8-d3d4-407e-8c15-6e74500e4d4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#digit-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digit-2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>98a09d58-ba9b-455d-ad66-a4e17d2606b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input input-text</value>
      <webElementGuid>702b4b30-a206-44dc-ab3c-a386e43faff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>36f14c90-a3d3-4d52-a2df-165934b5a9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>ea4a0163-1089-4610-ab7b-92313f524d48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digit-2</value>
      <webElementGuid>f0f9129f-e03f-40c2-a4ff-2a9e2bc570a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp[digit-2]</value>
      <webElementGuid>f88ddbfd-a643-4e9b-9970-3990d133a439</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-next</name>
      <type>Main</type>
      <value>digit-3</value>
      <webElementGuid>4d1153e5-268b-455c-839d-04ae163f0143</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previous</name>
      <type>Main</type>
      <value>digit-1</value>
      <webElementGuid>2d664a19-6e35-4b28-909f-6c48b16e9841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2a810217-ee6b-4ed1-94d5-7d860f0d9f38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digit-2&quot;)</value>
      <webElementGuid>c0a4c94c-208a-41da-92ac-3bdd662fbe48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digit-2']</value>
      <webElementGuid>6ffdb36f-b8f2-4b13-9c77-6019df8cc05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp']/div/input[2]</value>
      <webElementGuid>32537405-1cf1-43ab-9e45-433ff742dc1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input[2]</value>
      <webElementGuid>a193874e-aa43-4180-9359-c3c7439f863a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'digit-2' and @name = 'otp[digit-2]']</value>
      <webElementGuid>b3b826fc-4935-4aa6-abfd-d38112c97dd7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
