<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan kode OTP yang Anda terima di _12c735</name>
   <tag></tag>
   <elementGuidId>f81fbece-7f8d-4425-840d-852d3a0dd4e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#digit-4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digit-4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c1be3ac5-e0e4-4133-b95f-4729632e9940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input input-text</value>
      <webElementGuid>6b926a1c-3542-4e5c-8ed8-6614582c60f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ce6ac543-3e3b-476c-8b09-e1d2580902d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>18d817c5-68ce-4146-b27c-677a5e5c0d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digit-4</value>
      <webElementGuid>458ed113-9e27-41fa-973f-efcb47771dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp[digit-4]</value>
      <webElementGuid>53c8f4ed-1f4b-410f-a7b5-7ec45b3a8772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-previous</name>
      <type>Main</type>
      <value>digit-3</value>
      <webElementGuid>b0e56c6a-7cec-46f4-b8bf-08886b1d0006</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3b0cdf42-fc47-493e-8e34-a6a06cadc63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digit-4&quot;)</value>
      <webElementGuid>5c012c0e-5732-4d5e-8fa1-cc955b7947f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digit-4']</value>
      <webElementGuid>b84720da-07bc-48af-8bf8-d5e0f8a9fdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp']/div/input[4]</value>
      <webElementGuid>f94d2643-8ab8-4435-abde-5ebe74a0fc3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[4]</value>
      <webElementGuid>0384a53b-fa12-4723-b475-f0bfe29cce01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'digit-4' and @name = 'otp[digit-4]']</value>
      <webElementGuid>282c0f9b-0dcf-4014-9125-cf8c806a1f1b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
