<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Masukan kode OTP yang Anda terima di _d0a841</name>
   <tag></tag>
   <elementGuidId>34b61504-43d1-40c7-9123-c5c29e517baa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#digit-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digit-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>38664651-bdfa-416d-adc8-71f2662ac25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>otp-input input-text</value>
      <webElementGuid>0fb2be6a-c0b5-4e78-adb3-f8043ab6a2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>ffa4080b-430f-4688-af2f-b88ed7308312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>b3994753-9247-463b-a07d-52c2a8462909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digit-1</value>
      <webElementGuid>705bde4b-8e6f-4a8d-9f38-f43704acab0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otp[digit-1]</value>
      <webElementGuid>ce3f24d4-cc8b-475f-a99e-0cd3feaa8a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-next</name>
      <type>Main</type>
      <value>digit-2</value>
      <webElementGuid>e7e288de-8f03-404b-9e7b-3d5474746b14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f2791fa9-7a20-4227-b01a-c78703556c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digit-1&quot;)</value>
      <webElementGuid>5aef5f15-ff23-4b39-8abd-b54891f0a8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digit-1']</value>
      <webElementGuid>d0b6c77f-fa33-420f-af16-e7b4466f9ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-otp']/div/input</value>
      <webElementGuid>1024bce9-5f25-4085-81f9-0e72214c3752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/input</value>
      <webElementGuid>52502617-c322-4dc7-b416-ce6f7f614e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'digit-1' and @name = 'otp[digit-1]']</value>
      <webElementGuid>5599b9dc-a0f8-4231-86d8-55953a38d007</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
