<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Pria</name>
   <tag></tag>
   <elementGuidId>0e13a965-5c0a-40dd-9661-aaab1c2d3b5d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.field.choice.ingroup > label.label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='form-validate']/fieldset/div[7]/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a7890ac0-59c5-4622-9e34-665e4d8710db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>15070b59-1d46-42e8-9327-f42880fcef23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gender-option-1</value>
      <webElementGuid>c4f0156f-27ff-4e2a-84f9-5cbf0ebd6b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pria</value>
      <webElementGuid>60fbe7c3-ec15-4dc9-84a0-3a716dee25dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;form-validate&quot;)/fieldset[@class=&quot;fieldset create info&quot;]/div[@class=&quot;field field-additional gender required ingroup&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;field choice ingroup&quot;]/label[@class=&quot;label&quot;]</value>
      <webElementGuid>bef19c27-ddbc-49cf-aeb2-20d231c63169</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-validate']/fieldset/div[7]/div/div/label</value>
      <webElementGuid>8f2c9518-7e8b-4ffe-a24f-679c2f7263bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jenis Kelamin'])[1]/following::label[1]</value>
      <webElementGuid>e5b3983d-6f77-4341-89b2-cafcd3f348f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password (minimal 8 karakter)'])[1]/following::label[2]</value>
      <webElementGuid>ddacfa28-6b6e-4c51-af8a-bd0d20f447f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wanita'])[1]/preceding::label[1]</value>
      <webElementGuid>2cd6edea-2103-4149-aa08-ca7f2e6cc9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/label</value>
      <webElementGuid>828576b7-6f0c-425a-8243-93a57c5cb936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Pria' or . = 'Pria')]</value>
      <webElementGuid>94e7d0a7-91b7-4c45-b881-c70e498fab38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
