<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ubah_email-otp-input</name>
   <tag></tag>
   <elementGuidId>b437ce65-03d6-4d84-8af4-8949fa7dd3b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#email-otp-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='email-otp-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4527e25b-a237-4b6b-8534-27411bf414b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>5baebbba-feb6-492c-bce9-bbfe931c4f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ffbff2c8-0002-487d-a1bf-1041a7426876</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b5b24b67-5afc-45da-b9c6-d84f0d731aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>email-otp-input</value>
      <webElementGuid>a6c78550-b06f-4f5a-93ce-40edc00ffeb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>email-otp-input</value>
      <webElementGuid>3317347f-f1a5-46a2-ba59-326275772cbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email-otp-input</value>
      <webElementGuid>8d948262-17cd-4b71-bc41-fce6666c4799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;email-otp-input&quot;)</value>
      <webElementGuid>c3ef087e-d812-4472-8dc6-7e54baf2306d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='email-otp-input']</value>
      <webElementGuid>acbf7319-d66a-46bd-ae96-a0898f66bdd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div[6]/div/input</value>
      <webElementGuid>4e0d9713-ed10-4c3b-b777-9f9a41dd2697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>bc4d44ed-124b-4cd5-901b-f516c2c0bc55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'email-otp-input' and @name = 'email-otp-input']</value>
      <webElementGuid>52adcb12-c557-42ea-ad39-88efe8a84298</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
