<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Show_current-password</name>
   <tag></tag>
   <elementGuidId>03e6839c-f807-4885-829b-bd38702cbea1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='current-password']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#current-password</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77266639-dbf3-4d7a-86fb-b6e48c96dd72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PasswordInput_input_field__EWMIU undefined</value>
      <webElementGuid>e3da9d04-9a3f-42a5-9f7d-315065589654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>3237c378-cc40-4561-8f9f-31b03b9021fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>9574dcf4-74ca-4898-8555-02cb197144cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>current-password</value>
      <webElementGuid>89e4fcc9-ac4c-4c6b-aa70-361fdc7eceb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;current-password&quot;)</value>
      <webElementGuid>838082db-395c-4d82-8d50-44b0fdb4eb52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='current-password']</value>
      <webElementGuid>c28563e1-7551-494a-bcfc-3d80c62e7356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[4]/div/div/div[2]/form/div[2]/div[2]/input</value>
      <webElementGuid>0c2d8150-a3b0-4bcf-a54a-fc7c68f93666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>3287145b-e391-4a3c-ad9c-adc9e77bf06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'current-password' and @type = 'password' and @id = 'current-password']</value>
      <webElementGuid>9e490a83-d440-4b08-9983-75922788db78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
