<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Keluar</name>
   <tag></tag>
   <elementGuidId>624da6bb-b5ff-4bc6-8f30-16b0a38cb416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-stickyNewsletter__close--btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-stickyNewsletter__close--btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>32577c81-e665-4713-ad2b-2fa5ffd4f5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>9e3f829d-f2c1-4a6f-9ed6-90466a995510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-stickyNewsletter__close--btn</value>
      <webElementGuid>3e04d00f-ff47-4b45-9c4b-3cef122e0695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>b-stickyNewsletter__close--btn</value>
      <webElementGuid>6906352c-4736-4831-bf4a-a2fa776cc6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>e8de3a5b-9da3-4a0a-a0a5-6f933054318e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-stickyNewsletter__close--btn&quot;)</value>
      <webElementGuid>4e4b9a83-a7b9-4d67-aeda-22bc1f01dd4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='js-stickyNewsletter__close--btn']</value>
      <webElementGuid>63ffa193-8bed-49d2-94a7-3756adecc853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='page']/div/div[2]/div[2]/a</value>
      <webElementGuid>260e86fb-ec75-4fe3-953b-4744cccbaf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Keluar')]</value>
      <webElementGuid>1ad9a11d-e56a-4174-bfe1-0256dc467376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::a[1]</value>
      <webElementGuid>213bd5c8-b359-4862-a2b6-57ec53262d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sepertinya Anda telah berlangganan'])[1]/following::a[1]</value>
      <webElementGuid>330a5bcf-cdcd-42e8-967b-cf6abca7a859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diskon hingga Rp 75.000untuk pesanan Anda selanjutnya'])[1]/preceding::a[1]</value>
      <webElementGuid>06199589-41f6-4821-b248-42a1ae9f52cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masukkan email Anda untuk info dan penawaran ZALORA'])[1]/preceding::a[1]</value>
      <webElementGuid>4ca5ff0c-080e-4f27-bea2-d0e6e25613fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>926cc29e-a41d-455c-8857-3e9840ee67c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>96c374fd-d20e-45c5-96ee-9046e4b51aa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>0d841c34-7c20-47c5-8e04-ae753e5b1dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and @id = 'js-stickyNewsletter__close--btn' and (text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>e15f13c4-f04b-4934-8443-d0cb9885a8d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
