<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Konfirmasi dan Lanjutkan</name>
   <tag></tag>
   <elementGuidId>244b4e62-6c1f-4bce-b54c-1ac6383ca0d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='send']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2b65e0c3-3c5c-48f5-a148-92a179b7d5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn none--uppercase btn--medium btn--fluid fsxl mtl sel-new-account-submit-button register__btnSubmit</value>
      <webElementGuid>eefebc87-3106-453f-9867-645845acd817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8c065e3c-4709-44ce-a815-d591e832dd27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send</value>
      <webElementGuid>9cd480d8-1642-480f-82e7-a987202e27a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Konfirmasi dan Lanjutkan                    </value>
      <webElementGuid>56e55e00-ad87-4278-a602-07b81a39cc59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;send&quot;)</value>
      <webElementGuid>227e8cca-4e53-47ab-a7eb-1da0918ad476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='send']</value>
      <webElementGuid>bba25929-5d54-4508-9549-a47eb0d49aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account-create']/div[2]/button</value>
      <webElementGuid>a5a99877-3e1b-4634-a8e0-950794503105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya mau diskon Rp75.000, koleksi produk terbaru, dan berbagai fashion terkini di inbox saya!'])[1]/following::button[1]</value>
      <webElementGuid>6ccf5d03-9ef7-435d-868e-4bcecf7dd5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Saya ingin tetap login'])[1]/following::button[1]</value>
      <webElementGuid>d810e30f-24a1-4af0-b3c2-7d3979f8adde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Persyaratan dan Ketentuan'])[1]/preceding::button[1]</value>
      <webElementGuid>8c86c4de-c122-4df1-9afa-fd3c92a348cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Konfirmasi dan Lanjutkan']/parent::*</value>
      <webElementGuid>bc8f66f8-053c-4cb0-9429-9596681c36bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/button</value>
      <webElementGuid>b3605c28-ea1a-4142-af94-3ef96c7c741a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @id = 'send' and (text() = '
                        Konfirmasi dan Lanjutkan                    ' or . = '
                        Konfirmasi dan Lanjutkan                    ')]</value>
      <webElementGuid>3ac36a66-6211-46e9-a8a8-fdda5a5554d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
