<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__RegistrationFormemail</name>
   <tag></tag>
   <elementGuidId>ad0d6d13-29e4-4229-9042-3659bf85d8d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegistrationForm_email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegistrationForm_email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45c1e1a4-618f-4b1f-90f3-a78009dd1b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mts js-emailInputText ui-inputText</value>
      <webElementGuid>e0f43209-aae0-45d0-8743-15efa41cfb88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegistrationForm[email]</value>
      <webElementGuid>2c1ba0e5-36ed-4525-b3b2-4d930d52d0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegistrationForm_email</value>
      <webElementGuid>cc3c2d29-f932-49fa-93be-fb038a49bfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5103d4ad-5196-4770-a6dd-57d0c64473f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>dd2a50c9-88c2-4972-97c4-73384c1a60b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegistrationForm_email&quot;)</value>
      <webElementGuid>32e41d6c-8c5a-4e17-9972-7dcc5fc34753</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegistrationForm_email']</value>
      <webElementGuid>3c98c3f4-cd70-4780-9e82-0c206c40e77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account-create']/div[2]/div/input</value>
      <webElementGuid>bd097941-36f2-43d7-9896-3043fd5a859e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>b358e786-36b5-4d79-957b-463964f24b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'RegistrationForm[email]' and @id = 'RegistrationForm_email' and @type = 'text']</value>
      <webElementGuid>9a3b144a-114b-4c3b-bd11-994bfafda3e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
