<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sembunyikan_RegistrationFormpassword</name>
   <tag></tag>
   <elementGuidId>8af132c6-6ada-494e-a07f-fc016ed65bcf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegistrationForm_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegistrationForm_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1618267-da8d-419e-9ce8-d90caf8b8a91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputPassword</value>
      <webElementGuid>caf0a11e-07e6-4a64-b2d2-40bfa92944ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegistrationForm[password]</value>
      <webElementGuid>ede25f68-8331-448e-a3f9-09b2955fc5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegistrationForm_password</value>
      <webElementGuid>88c04ad5-5ad6-4197-8341-a48670f9c844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>c3fb8efc-b249-418a-87af-1d7f0110f120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>0fbd7282-732c-41e7-80ff-438c38fecfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegistrationForm_password&quot;)</value>
      <webElementGuid>fa876188-6048-42b5-b897-f8d5840f8d01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegistrationForm_password']</value>
      <webElementGuid>a65b8022-25eb-4387-b02c-da5c8e35829a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='js-password-input']/input[2]</value>
      <webElementGuid>56f4e962-ce2b-442e-b582-1c61b539d11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input[2]</value>
      <webElementGuid>b5f8e335-3171-417b-b90b-dd57d6ccd1a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'RegistrationForm[password]' and @id = 'RegistrationForm_password' and @type = 'password']</value>
      <webElementGuid>673bacf6-afee-4e91-9866-17ad6d0dfa53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
