<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Nama Depan_RegistrationFormfirst_name</name>
   <tag></tag>
   <elementGuidId>a474b9e7-b757-49bf-854f-d4c1d2b75329</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegistrationForm_first_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RegistrationForm_first_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef9006e6-1782-4112-97e8-16374c350bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>js-registrationForm__firstname js-none-special-characters ui-inputText</value>
      <webElementGuid>77e63b82-8656-451b-9feb-612214eaeb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegistrationForm[first_name]</value>
      <webElementGuid>291f3d7a-67cd-4a60-afad-52cb4a20761d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegistrationForm_first_name</value>
      <webElementGuid>e9fcefe8-33a3-4839-a8d5-e84176ce23bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cff58a06-3a10-4a27-bd17-7de4200d7539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>ece95b71-5667-44b7-9b5a-9679ff638734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegistrationForm_first_name&quot;)</value>
      <webElementGuid>4027f853-96bc-4367-bfd0-d5a3269e8e11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RegistrationForm_first_name']</value>
      <webElementGuid>413ceb3e-a72a-473d-bc26-2924be547f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account-create']/div[2]/div[5]/div/div/input</value>
      <webElementGuid>9c7c5131-0d44-4c36-80eb-b63230f62fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>a06272d0-41ad-45a4-a94e-7b4b34321ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'RegistrationForm[first_name]' and @id = 'RegistrationForm_first_name' and @type = 'text']</value>
      <webElementGuid>ce07d1ea-c464-4602-b0b4-dfbb4d0e8535</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
