<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JanuariFebruariMaretAprilMeiJuniJuli_13de9b</name>
   <tag></tag>
   <elementGuidId>b5b89f0b-7c13-4399-ae0a-6b329398ce65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RegistrationForm_month</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RegistrationForm_month']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>16db48ab-b66d-4c89-b06c-0abf4e15d6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>register__month--select</value>
      <webElementGuid>a1740811-3372-421a-bf27-7fb1691d2b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegistrationForm[month]</value>
      <webElementGuid>bbd68a7b-8a81-4569-97eb-767346e0577e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegistrationForm_month</value>
      <webElementGuid>9cc02d1e-d2f3-4870-b7b6-22d06a819844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

Januari
Februari
Maret
April
Mei
Juni
Juli
Agustus
September
Oktober
November
Desember
</value>
      <webElementGuid>020401f2-ca8d-434a-a79a-c868b505ebb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegistrationForm_month&quot;)</value>
      <webElementGuid>6183c248-d9d2-4dff-8872-758787a06e86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RegistrationForm_month']</value>
      <webElementGuid>0fe0532c-c3ad-495a-8ef9-f6be9347246c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-account-create']/div[2]/div[6]/div/div/div[2]/select</value>
      <webElementGuid>69950497-82d4-4861-bd67-997c659c8926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih hari'])[1]/following::select[1]</value>
      <webElementGuid>02b0b0f9-8264-42a7-ba1b-7f47bc05a2a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanggal'])[1]/following::select[1]</value>
      <webElementGuid>c9bb22cc-fd6b-435d-8801-88c8e86ed599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bulan'])[1]/preceding::select[1]</value>
      <webElementGuid>db0749d6-faef-45b4-9f3f-9323130728b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih bulan'])[1]/preceding::select[1]</value>
      <webElementGuid>36b0aa3c-b318-4cdc-81e1-3dd7ab32c65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>31e14d88-aa75-4cce-890c-83157bd21912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'RegistrationForm[month]' and @id = 'RegistrationForm_month' and (text() = '

Januari
Februari
Maret
April
Mei
Juni
Juli
Agustus
September
Oktober
November
Desember
' or . = '

Januari
Februari
Maret
April
Mei
Juni
Juli
Agustus
September
Oktober
November
Desember
')]</value>
      <webElementGuid>aac03825-07ff-4897-9550-0333ee362315</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
