<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pria_radiomark</name>
   <tag></tag>
   <elementGuidId>013a76b0-b567-4d97-b3ce-08986d43faab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='RegistrationForm_gender']/label[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60b8ac20-80a0-4086-b07a-c6bdf7a95254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radiomark</value>
      <webElementGuid>80edf09e-0796-4422-9929-1afacf99219a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegistrationForm_gender&quot;)/label[@class=&quot;radioLabel radiobutton__container&quot;]/span[@class=&quot;radiomark&quot;]</value>
      <webElementGuid>d860de2d-a228-452c-b2e1-e7e40e7adcb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='RegistrationForm_gender']/label[2]/span</value>
      <webElementGuid>bdfe704b-a290-460b-9150-6f120e7149e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[2]/span</value>
      <webElementGuid>56799d7f-af29-4358-8c72-a4d62ffd35bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
