<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Privasi</name>
   <tag></tag>
   <elementGuidId>ffa6c516-fd1d-4f27-b213-0dcc7c3fa6ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[4]/div/div/div[2]/div[2]/div/ul/li[10]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bc0f3177-b10e-42be-9d84-ac1d1eacbdc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_3KnwL _3yAjN</value>
      <webElementGuid>0caeb3a4-675e-4407-82f4-ec1117da0709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/privacy</value>
      <webElementGuid>96449979-bdc4-4fd5-ac73-82ee4bb4df44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Privasi</value>
      <webElementGuid>9e66dfb8-4829-46ac-ad2e-ae191b9251d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;_3W86r _1Xlh1&quot;]/div[1]/div[@class=&quot;_2rYrl&quot;]/div[@class=&quot;_33Mo9&quot;]/div[@class=&quot;_3ky4c&quot;]/div[@class=&quot;_3dgVT&quot;]/ul[@class=&quot;R1UFe&quot;]/li[@class=&quot;_1KXNm&quot;]/a[@class=&quot;_3KnwL _3yAjN&quot;]</value>
      <webElementGuid>8d5395c0-c6f1-414a-a1da-33ae657fe7e8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[4]/div/div/div[2]/div[2]/div/ul/li[10]/a</value>
      <webElementGuid>ecccf638-902e-4aef-a164-3d65c7dedc94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Privasi')]</value>
      <webElementGuid>0e2bec11-c038-48b9-b903-21948cdece22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ketentuan'])[1]/following::a[1]</value>
      <webElementGuid>6ba8bacc-4d76-4d21-8af2-3b6d4fed4765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INVESTOR'])[1]/following::a[2]</value>
      <webElementGuid>08be2211-7379-40ee-b24b-3a423eaa5939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::a[1]</value>
      <webElementGuid>22b1169d-c358-49b7-8bbd-3a3b7fa92ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::a[1]</value>
      <webElementGuid>15955b5e-6b3e-4039-8d62-dcf723797fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Privasi']/parent::*</value>
      <webElementGuid>55bab02d-62e7-423e-b229-2266f72c57aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/privacy')]</value>
      <webElementGuid>7d1974ab-b152-45e8-b698-a32e986de3e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>5bdf5f34-6a50-4319-a4f5-b173bc00876d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/privacy' and (text() = 'Privasi' or . = 'Privasi')]</value>
      <webElementGuid>ff0191c5-17fa-4cf6-ae23-654eba06be03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
