<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Lainnya_J0tZA</name>
   <tag></tag>
   <elementGuidId>594a676b-7889-4128-b8e0-e279347714db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div[2]/div[11]/span/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.J0tZA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f182bf87-ea51-4627-863e-24dd76bbcd75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>J0tZA</value>
      <webElementGuid>97f57d96-4cca-4e09-aa3b-f9f819a57c4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;_1kJpR _3g2C1&quot;]/div[@class=&quot;_1bdcY&quot;]/div[@class=&quot;_3E4oM _3jIW4&quot;]/span[@class=&quot;_3_CAz _2QyqO _3jIW4&quot;]/div[@class=&quot;J0tZA&quot;]</value>
      <webElementGuid>748f535b-d48c-4879-a76f-8f129eb19869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>702777ea-6d6b-4757-86af-cf4b52940ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>J0tZA</value>
      <webElementGuid>c90cda86-c165-4f9e-ad52-1a9612f9d3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;_1kJpR _3g2C1&quot;]/div[@class=&quot;_1bdcY&quot;]/div[@class=&quot;_3E4oM _3jIW4&quot;]/span[@class=&quot;_3_CAz _2QyqO _3jIW4&quot;]/div[@class=&quot;J0tZA&quot;]</value>
      <webElementGuid>cf0f695b-9194-4e88-b836-a49ca2ebf49a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div[2]/div[11]/span/div</value>
      <webElementGuid>f8e938ca-91ed-4b97-8157-a1fbdcc6f652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lainnya'])[1]/following::div[7]</value>
      <webElementGuid>44b9197e-04c5-43f5-8efe-4ea1e88e8f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toko'])[1]/following::div[10]</value>
      <webElementGuid>a587d7fb-0b5e-4699-abac-42216f5cb8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Akun'])[1]/preceding::div[1]</value>
      <webElementGuid>d4e14b31-e404-4f3d-8aa4-4df611de165f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profilmu'])[1]/preceding::div[2]</value>
      <webElementGuid>f1a0e9a9-e5cc-41e7-82ac-7088b2f18f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/span/div</value>
      <webElementGuid>46d90fc0-1a4c-4134-b5ee-ed564c5c61ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
